[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install --prefix server && node server/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
